package com.vit.sgpa.service;

import com.lowagie.text.*;
import com.lowagie.text.pdf.PdfPCell;
import com.lowagie.text.pdf.PdfPTable;
import com.lowagie.text.pdf.PdfWriter;
import com.vit.sgpa.dto.ResultResponse;
import com.vit.sgpa.dto.SubjectResult;
import org.springframework.stereotype.Service;

import java.awt.Color;
import java.io.ByteArrayOutputStream;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;

@Service
public class PdfService {

    private static final Color PRIMARY = new Color(26, 35, 126);
    private static final Color ROW_ALT = new Color(242, 242, 247);

    public byte[] generateResultPdf(
            String studentName,
            String email,
            String semesterLabel,
            ResultResponse result
    ) {
        try {
            Document document = new Document(PageSize.A4, 50, 50, 50, 50);
            ByteArrayOutputStream out = new ByteArrayOutputStream();
            PdfWriter.getInstance(document, out);
            document.open();

            Font titleFont = new Font(Font.HELVETICA, 20, Font.BOLD, PRIMARY);
            Font subtitleFont = new Font(Font.HELVETICA, 10, Font.NORMAL, Color.GRAY);
            Font infoFont = new Font(Font.HELVETICA, 12, Font.NORMAL, Color.BLACK);
            Font tableHeaderFont = new Font(Font.HELVETICA, 11, Font.BOLD, Color.WHITE);
            Font tableCellFont = new Font(Font.HELVETICA, 10.5f, Font.NORMAL, Color.BLACK);
            Font sgpaFont = new Font(Font.HELVETICA, 16, Font.BOLD, PRIMARY);
            Font footerFont = new Font(Font.HELVETICA, 8, Font.ITALIC, Color.GRAY);

            Paragraph title = new Paragraph("VIT Semester Result Sheet", titleFont);
            title.setAlignment(Element.ALIGN_CENTER);
            document.add(title);

            Paragraph subtitle = new Paragraph("Generated by VIT SGPA Calculator", subtitleFont);
            subtitle.setAlignment(Element.ALIGN_CENTER);
            subtitle.setSpacingAfter(20);
            document.add(subtitle);

            document.add(new Paragraph("Student Name: " + studentName, infoFont));
            document.add(new Paragraph("Email: " + email, infoFont));
            document.add(new Paragraph("Semester: " + semesterLabel, infoFont));
            document.add(new Paragraph(
                    "Date: " + LocalDate.now().format(DateTimeFormatter.ofPattern("dd MMM yyyy")),
                    infoFont
            ));

            Paragraph spacer = new Paragraph(" ");
            spacer.setSpacingAfter(10);
            document.add(spacer);

            PdfPTable table = new PdfPTable(6);
            table.setWidthPercentage(100);
            table.setWidths(new float[]{2.4f, 1f, 1f, 1f, 1f, 1f});

            String[] headers = {"Subject", "MSE", "ESE", "Final", "Grade", "Credits"};
            for (String h : headers) {
                PdfPCell cell = new PdfPCell(new Phrase(h, tableHeaderFont));
                cell.setBackgroundColor(PRIMARY);
                cell.setPadding(8);
                cell.setHorizontalAlignment(Element.ALIGN_LEFT);
                table.addCell(cell);
            }

            boolean alt = false;
            for (SubjectResult s : result.getSubjects()) {
                Color bg = alt ? ROW_ALT : Color.WHITE;
                table.addCell(styledCell(s.getName(), tableCellFont, bg));
                table.addCell(styledCell(String.valueOf(s.getMse()), tableCellFont, bg));
                table.addCell(styledCell(String.valueOf(s.getEse()), tableCellFont, bg));
                table.addCell(styledCell(String.valueOf(s.getFinalMarks()), tableCellFont, bg));
                table.addCell(styledCell(s.getGrade(), tableCellFont, bg));
                table.addCell(styledCell(String.valueOf(s.getCredits()), tableCellFont, bg));
                alt = !alt;
            }

            document.add(table);

            Paragraph spacer2 = new Paragraph(" ");
            spacer2.setSpacingAfter(15);
            document.add(spacer2);

            Paragraph totalCredits = new Paragraph(
                    "Total Credits: " + result.getTotalCredits(), infoFont
            );
            totalCredits.setSpacingAfter(8);
            document.add(totalCredits);

            Paragraph sgpa = new Paragraph("SGPA: " + result.getSgpa(), sgpaFont);
            sgpa.setSpacingAfter(40);
            document.add(sgpa);

            Paragraph footer = new Paragraph(
                    "This is a system-generated document from the VIT SGPA Calculator and is not an official transcript.",
                    footerFont
            );
            footer.setAlignment(Element.ALIGN_CENTER);
            document.add(footer);

            document.close();
            return out.toByteArray();
        } catch (DocumentException e) {
            throw new RuntimeException("Failed to generate PDF: " + e.getMessage(), e);
        }
    }

    private PdfPCell styledCell(String text, Font font, Color bg) {
        PdfPCell cell = new PdfPCell(new Phrase(text, font));
        cell.setBackgroundColor(bg);
        cell.setPadding(7);
        return cell;
    }
}
